### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jhejderup** [praezi/rust-emse-2020#1]
- [x] Add separate analysis of the paper in a file
- [x] Expand with more instructions
- [x] Audit the scripts
- [x] Dataset - CG Corpus

**Comment by jhejderup** [comment]
Data to include

- [x] CDN.json
- [x] PDN.json
- [x] raw call graphs
